### ISSUE TITLE
Failed to convert solution

### ISSUE THREAD

**Issue by lu8848** [twsouthwick/NuGetPackageConfigConverter#11]
### Installed product versions
- Visual Studio: [VS 2015 Enterprise]
- This extension: 0.1.16

### Description
Right click the solution to convert in VS, and got this in the middle:
System.AggregateException: One or more errors occurred. ---> System.ArgumentException: URI formats are not supported.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents)
   at NuGetPackageConfigConverter.PackageManagerConverter.CreateProjectJson(Project project) in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\PackageManagerConverter.cs:line 133
   at NuGetPackageConfigConverter.PackageManagerConverter.AddProjectJson(IEnumerable`1 projects, CancellationToken token) in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\PackageManagerConverter.cs:line 82
   at NuGetPackageConfigConverter.PackageManagerConverter.<>c__DisplayClass7_0.<ConvertAsync>b__0(ConverterUpdateViewModel model, CancellationToken token) in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\PackageManagerConverter.cs:line 71
   at NuGetPackageConfigConverter.DialogWindowConverterViewProvider.<>c__DisplayClass0_2.<ShowAsync>b__0() in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\DialogWindowConverterViewProvider.cs:line 37
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentException: URI formats are not supported.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents)
   at NuGetPackageConfigConverter.PackageManagerConverter.CreateProjectJson(Project project) in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\PackageManagerConverter.cs:line 133
   at NuGetPackageConfigConverter.PackageManagerConverter.AddProjectJson(IEnumerable`1 projects, CancellationToken token) in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\PackageManagerConverter.cs:line 82
   at NuGetPackageConfigConverter.PackageManagerConverter.<>c__DisplayClass7_0.<ConvertAsync>b__0(ConverterUpdateViewModel model, CancellationToken token) in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\PackageManagerConverter.cs:line 71
   at NuGetPackageConfigConverter.DialogWindowConverterViewProvider.<>c__DisplayClass0_2.<ShowAsync>b__0() in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\DialogWindowConverterViewProvider.cs:line 37<---

**Comment by twsouthwick** [comment]
What kind of project was it?

**Comment by twsouthwick** [comment]
Without a repro, I can't fix anything. I'll close for now, but please try upgrading to the latest version (0.1.30) and try again. Feel free to reopen if you hit the issue again.
