### ISSUE TITLE
Error performing conversion

### ISSUE THREAD

**Issue by johnnyb** [twsouthwick/NuGetPackageConfigConverter#12]
### Installed product versions
- Visual Studio:  2017 Community  (2015 is also installed)
- This extension: I don't know the version but I literally *just* installed it

### Description
Right-clicked on a solution and did the convert, got the error below

System.AggregateException: One or more errors occurred. ---> System.NotImplementedException: Not implemented (Exception from HRESULT: 0x80004001 (E_NOTIMPL))
   at EnvDTE.Project.get_FullName()
   at NuGetPackageConfigConverter.VSExtensions.<GetProjects>d__1.MoveNext() in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\VSExtensions.cs:line 25
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NuGetPackageConfigConverter.PackageManagerConverter.<>c__DisplayClass7_0.<ConvertAsync>b__0(ConverterUpdateViewModel model, CancellationToken token) in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\PackageManagerConverter.cs:line 46
   at NuGetPackageConfigConverter.DialogWindowConverterViewProvider.<>c__DisplayClass0_2.<ShowAsync>b__0() in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\DialogWindowConverterViewProvider.cs:line 37
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.NotImplementedException: Not implemented (Exception from HRESULT: 0x80004001 (E_NOTIMPL))
   at EnvDTE.Project.get_FullName()
   at NuGetPackageConfigConverter.VSExtensions.<GetProjects>d__1.MoveNext() in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\VSExtensions.cs:line 25
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NuGetPackageConfigConverter.PackageManagerConverter.<>c__DisplayClass7_0.<ConvertAsync>b__0(ConverterUpdateViewModel model, CancellationToken token) in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\PackageManagerConverter.cs:line 46
   at NuGetPackageConfigConverter.DialogWindowConverterViewProvider.<>c__DisplayClass0_2.<ShowAsync>b__0() in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\DialogWindowConverterViewProvider.cs:line 37<---

**Comment by twsouthwick** [comment]
What kind of projects do you have in your solution? Looks like I'm having trouble extracting the project name

**Comment by twsouthwick** [comment]
The part of code that hit this exception has been rewritten. I'm closing this for now as I don't have a way to repro the issue - feel free to reopen if you hit the error again.
