### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MarkBeharrell** [twsouthwick/NuGetPackageConfigConverter#32]
System.AggregateException: One or more errors occurred. ---> System.Runtime.InteropServices.COMException: Error deleting file 'packages.config'.  Unable to delete 'packages.config'.  The system call level is not correct.

   at EnvDTE.ProjectItem.Delete()
   at NuGetPackageConfigConverter.PackageManagerConverter.RemoveDependencyFiles(Project project) in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\PackageManagerConverter.cs:line 167
   at NuGetPackageConfigConverter.PackageManagerConverter.RemoveDependencyFiles(IEnumerable`1 projects) in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\PackageManagerConverter.cs:line 159
   at NuGetPackageConfigConverter.PackageManagerConverter.<>c__DisplayClass7_0.<ConvertAsync>b__0(ConverterUpdateViewModel model, CancellationToken token) in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\PackageManagerConverter.cs:line 61
   at NuGetPackageConfigConverter.DialogWindowConverterViewProvider.<>c__DisplayClass0_2.<ShowAsync>b__0() in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\DialogWindowConverterViewProvider.cs:line 37
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Runtime.InteropServices.COMException (0x8007007C): Error deleting file 'packages.config'.  Unable to delete 'packages.config'.  The system call level is not correct.

   at EnvDTE.ProjectItem.Delete()
   at NuGetPackageConfigConverter.PackageManagerConverter.RemoveDependencyFiles(Project project) in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\PackageManagerConverter.cs:line 167
   at NuGetPackageConfigConverter.PackageManagerConverter.RemoveDependencyFiles(IEnumerable`1 projects) in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\PackageManagerConverter.cs:line 159
   at NuGetPackageConfigConverter.PackageManagerConverter.<>c__DisplayClass7_0.<ConvertAsync>b__0(ConverterUpdateViewModel model, CancellationToken token) in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\PackageManagerConverter.cs:line 61
   at NuGetPackageConfigConverter.DialogWindowConverterViewProvider.<>c__DisplayClass0_2.<ShowAsync>b__0() in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\DialogWindowConverterViewProvider.cs:line 37<---

**Comment by twsouthwick** [comment]
This project will not be maintained as support for converting to PackageReference is included in VS 15.7+: https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference
