### ISSUE TITLE
Null Reference Exception

### ISSUE THREAD

**Issue by carldebilly** [twsouthwick/NuGetPackageConfigConverter#34]
### Installed product versions
- Visual Studio: 2017 Enterprise 15.9.0 Preview 6.0
- This extension: 4.6.0
- Project types within the solution being converted
.net4.5 "classic" libraries

### Description
Got this error, pasted by the plugin:
```
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at NuGetPackageConfigConverter.PackageManagerConverter.AddRestoreProjectStyle(String path) in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\PackageManagerConverter.cs:line 204
   at NuGetPackageConfigConverter.PackageManagerConverter.RefreshSolution(Solution sln, IEnumerable`1 projects) in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\PackageManagerConverter.cs:line 193
   at NuGetPackageConfigConverter.PackageManagerConverter.<>c__DisplayClass7_0.<ConvertAsync>b__0(ConverterUpdateViewModel model, CancellationToken token) in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\PackageManagerConverter.cs:line 63
   at NuGetPackageConfigConverter.DialogWindowConverterViewProvider.<>c__DisplayClass0_2.<ShowAsync>b__0() in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\DialogWindowConverterViewProvider.cs:line 37
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at NuGetPackageConfigConverter.PackageManagerConverter.AddRestoreProjectStyle(String path) in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\PackageManagerConverter.cs:line 204
   at NuGetPackageConfigConverter.PackageManagerConverter.RefreshSolution(Solution sln, IEnumerable`1 projects) in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\PackageManagerConverter.cs:line 193
   at NuGetPackageConfigConverter.PackageManagerConverter.<>c__DisplayClass7_0.<ConvertAsync>b__0(ConverterUpdateViewModel model, CancellationToken token) in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\PackageManagerConverter.cs:line 63
   at NuGetPackageConfigConverter.DialogWindowConverterViewProvider.<>c__DisplayClass0_2.<ShowAsync>b__0() in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\DialogWindowConverterViewProvider.cs:line 37<---
```

**Comment by twsouthwick** [comment]
This project will not be maintained as support for converting to PackageReference is included in VS 15.7+: https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference
