### ISSUE TITLE
Crash when converting solution with shared project

### ISSUE THREAD

**Issue by picrap** [twsouthwick/NuGetPackageConfigConverter#4]
Hi, it almost worked... But did not :smile: 

Here is the exception detail provided by your application.

```
System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at NuGetPackageConfigConverter.PackageManagerConverter.GetProjectItem(ProjectItems items, String name) in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\PackageManagerConverter.cs:line 239
   at NuGetPackageConfigConverter.PackageManagerConverter.GetPackageConfig(Project project) in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\PackageManagerConverter.cs:line 186
   at NuGetPackageConfigConverter.PackageManagerConverter.<>c.<ConvertAsync>b__6_1(Project p) in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\PackageManagerConverter.cs:line 46
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at NuGetPackageConfigConverter.PackageManagerConverter.<>c__DisplayClass6_0.<ConvertAsync>b__0(ConverterUpdateViewModel model, CancellationToken token) in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\PackageManagerConverter.cs:line 44
   at NuGetPackageConfigConverter.DialogWindowConverterViewProvider.<>c__DisplayClass0_2.<ShowAsync>b__0() in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\DialogWindowConverterViewProvider.cs:line 37
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at NuGetPackageConfigConverter.PackageManagerConverter.GetProjectItem(ProjectItems items, String name) in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\PackageManagerConverter.cs:line 239
   at NuGetPackageConfigConverter.PackageManagerConverter.GetPackageConfig(Project project) in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\PackageManagerConverter.cs:line 186
   at NuGetPackageConfigConverter.PackageManagerConverter.<>c.<ConvertAsync>b__6_1(Project p) in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\PackageManagerConverter.cs:line 46
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at NuGetPackageConfigConverter.PackageManagerConverter.<>c__DisplayClass6_0.<ConvertAsync>b__0(ConverterUpdateViewModel model, CancellationToken token) in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\PackageManagerConverter.cs:line 44
   at NuGetPackageConfigConverter.DialogWindowConverterViewProvider.<>c__DisplayClass0_2.<ShowAsync>b__0() in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\DialogWindowConverterViewProvider.cs:line 37<---
```

**Comment by picrap** [comment]
After a few tests, it appears that a shared project (shproj) caused the problem. Removing it before conversion worked.

**Comment by twsouthwick** [comment]
Thanks for the report! I haven't tried it on a shared project. Do you have a public repro case I can use?

**Comment by picrap** [comment]
Lazy boy! 😉 
https://github.com/ArxOne/MrAdvice.MVVM.git

**Comment by twsouthwick** [comment]
Thanks for indulging my laziness :) I'll take a look

**Comment by twsouthwick** [comment]
Found the issue - please check out the CI build at http://vsixgallery.com/extension/NuGetPackageConfigConverter.Taylor%20Southwick.dd0141da-d26f-4013-8b78-72723a313486/? You'll need at least v0.1.10

**Comment by picrap** [comment]
Thanks! 👍
